platform :ios, '11.0'

target 'CCC' do
  pod 'AppAuth', '= 0.94'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'Firebase/Core'
  pod 'Firebase/Database'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end